const APP_PATHS = {
  WelcomeDashboard: '/welcome',
  Inbox: '/inbox',
  Spam: '/spam',
  Chat: '/chat',
  Spaces: '/spaces',
  Channels: '/channels',
  ChannelDetails: (adr?: string) => `/channels/${adr ?? ':id'}`,
  ChannelDashboard: (adr?: string) => `/channel/${adr ?? ':id'}`,
  CreateChannel: '/channel/create',
  Dashboard: '/dashboard',
  AddNewChain: '/add-new-chain',
  DiscordVerification: '/discord/verification',
  Rewards: '/points',
  RewardsActivities: '/points/activity',
  RewardsLeaderboard: '/points/leaderboard',
  PointsVault: '/points/vault',
  Send: '/send',
  Receive: '/receive',
  Govern: '/govern',
  Snap: '/snap',
  Yield: '/yield',
  YieldV2: '/yieldv2',
  Rockstar: '/rockstar',
  Gratitude: '/gratitude',
  LiveWalkthrough: '/live_walkthrough',
  ComingSoon: '/comingsoon',
  NotAvailable: '/notavailable',
  FAQ: '/faq',
  Internal: '/internal',
  Support: '/support',
  UserSettings: '/user/settings',
  ChannelSettings: '/channel/settings',
  ClaimGalxe: 'claim/galxe',
};

export default APP_PATHS;
