const NavigationList = {
    primary: {
      communicate: {
        src: "svg/communicate.svg",
        iconFactory: null,
        name: 'Communicate',
        title: 'Communicate Tab',
        alt: 'Communicate Tab Icon',
        href: null,
        newTab: false,
        isRoute: true,
        hasMenuLogic: true,
        opened: true,
  
        drilldown: {
          inbox: {
            src: "svg/feedbox.svg",
            iconFactory: null,
            name: 'Inbox',
            title: 'Inbox',
            alt: 'Open Inbox',
            href: '/inbox',
            newTab: false,
            isRoute: true,
            hasMenuLogic: true,
          },
          spam: {
            src: "svg/feedbox.svg",
            iconFactory: null,
            name: 'Spam',
            title: 'Spam',
            alt: 'Open Spam',
            href: '/spam',
            newTab: false,
            isRoute: true,
            hasMenuLogic: true,
          },  
          channels: {
            src: "svg/channel.svg",
            iconFactory: null,
            name: 'Channels',
            title: 'Browse Channels',
            alt: 'Open Channels',
            href: '/channels',
            newTab: false,
            isRoute: true,
            hasMenuLogic: true,
          },
          createChannel: {
            src: "svg/channeladmin.svg",
            iconFactory: null,
            name: 'Create Channel',
            title: 'Create Channel',
            alt: 'Create Channels / Dashboard',
            href: '/dashboard',
            newTab: false,
            isRoute: true,
            hasMenuLogic: true,
          },
        }
      },
      govern: {
        src: "svg/govern.svg",
        iconFactory: null,
        name: 'Govern',
        title: 'Governance Tab',
        alt: 'Governance Tab Icon',
        href: '/govern',
        newTab: false,
        opened: false,
        isRoute: true,
        hasMenuLogic: true,
      },
      incentives: {
        src: "svg/incentive.svg",
        iconFactory: null,
        name: 'Incentives',
        title: 'Check Incentives Tab',
        alt: 'Communicate Tab Icon',
        href: null,
        newTab: false,
        opened: true,
        isRoute: true,
        hasMenuLogic: true,
  
        drilldown: {
          yield: {
            src: "svg/yield.svg",
            iconFactory: null,
            name: 'Yield Farming',
            title: 'Yield Farming',
            alt: 'Open Yield Farming',
            href: '/yield',
            newTab: false,
            isRoute: true,  
            hasMenuLogic: true,
          },
          rockstars: {
            src: "svg/rockstars.svg",
            iconFactory: null,
            name: 'Rockstars of EPNS',
            title: 'Check Rockstars of EPNS',
            alt: 'Open Inbox',
            href: '/rockstar',
            newTab: false,
            isRoute: true,
            hasMenuLogic: true,
          },
          airdrop: {
            src: "svg/gratitude.svg",
            iconFactory: null,
            name: 'Gratitude Drop',
            title: 'Check Gratitude Drop',
            alt: 'Open Gratitude Drop',
            href: '/gratitude',
            newTab: false,
            isRoute: true,
            hasMenuLogic: true,
          },      
        }
      }
    },
    secondary: {
      latest: {
        src: "svg/channel.svg",
        iconFactory: null,
        name: 'Latest',
        title: 'Checkout latest news',
        alt: "Open What's Latest",
        href: 'https://staging-dapp.epns.io',
        newTab: true,
        opened: false,
        isRoute: false,
        isMenuLogic: false,
      },
      walkthrough: {
        src: "svg/channel.svg",
        iconFactory: null,
        name: 'Walkthrough',
        title: 'Start Walkthrough Tutorial',
        alt: 'Start Walkthrough Tutorial',
        href: '/walkthrough',
        newTab: false,
        opened: false,
        isRoute: false,
        isMenuLogic: false,
      },
      staging: {
        src: "svg/channel.svg",
        iconFactory: null,
        name: 'Staging Interface',
        title: 'Checkout staging interface',
        alt: 'Goto staging interface',
        href: 'https://staging-app.epns.io',
        newTab: true,
        opened: false,
        isRoute: false,
        isMenuLogic: false,
      },
      support: {
        src: "svg/channel.svg",
        iconFactory: null,
        name: 'Support',
        title: 'Open a support ticket',
        alt: 'Open Support Ticket',
        href: 'https://staging-dapp.epns.io',
        newTab: true,
        opened: false,
        isRoute: false,
        isMenuLogic: false,
      },
    },
    social: {
      twitter: {
        src: "BsTwitter",
        iconFactory: 'BsTwitter',
        name: null,
        title: 'Visit Twitter',
        alt: 'Open Twitter',
        href: 'https://twitter.com/epnsproject',
        newTab: true,
        isRoute: false,
        isMenuLogic: false,
      },
      telegram: {
        src: "FaTelegramPlane",
        iconFactory: "FaTelegramPlane",
        name: null,
        title: 'Visit Telegram',
        alt: 'Open Telegram',
        href: 'https://t.me/epnsproject',
        newTab: true,
        isRoute: false,
        isMenuLogic: false,
      },  
      discord: {
        src: "BsDiscord",
        iconFactory: "BsDiscord",
        name: null,
        title: 'Visit Twitter',
        alt: 'Open Twitter',
        href: 'https://twitter.com/epnsproject',
        newTab: true,
        isRoute: false,
        isMenuLogic: false,
      },
      medium: {
        src: "FaMedium",
        iconFactory: "FaMedium",
        name: null,
        title: 'Visit Medium',
        alt: 'Open Medium',
        href: 'https://medium.com/@epnsproject',
        newTab: true,
        isRoute: false,
        isMenuLogic: false,
      },
      github: {
        src: "FaGithub",
        iconFactory: "FaGithub",
        name: 'Create Channel',
        title: 'Create Channel',
        alt: 'Create Channels / Dashboard',
        href: 'https://github.com/ethereum-push-notification-service',
        newTab: true,
        isRoute: false,
        isMenuLogic: false,
      },
    }
  }
  
  
  export default NavigationList;
  